## render.yaml
services:
  - type: web
    name: vixproxy
    env: node
    plan: free
    region: frankfurt  # Render supporta regioni come frankfurt (equivalente a fra)
    buildCommand: npm install
    startCommand: node proxy.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    httpPort: 3000
    autoStop: true  # Equivalente a auto_stop_machines
    minInstances: 0  # Equivalente a min_machines_running
    maxInstances: 1
    resources:
      memoryMB: 1024
      cpuUnits: 1000  # 1 vCPU shared